use diesel::prelude::*;

use crate::schema::admins; // refers to the schema file generated by diesel
use serde::{Serialize, Deserialize}; // makes object of this class json serializable, we will convert these objects to json and send to user. 

#[derive(Queryable, PartialEq, Serialize, Debug)] // these annotation adds extra functionality to objects of this struct, Debug is for printing in console `dbg!(todo)`
pub struct Admin {
    pub admin_id: Option<i32>,
    pub username: String,
    pub pass: String,
    pub email: String,
    pub token: Option<String>,
    pub confirmed: bool,
}

#[derive(Insertable, Deserialize, Serialize, Debug, Clone)]
#[diesel(table_name = admins)]
pub struct NewAdmin<'a> {
    pub username: &'a str,
    pub pass: &'a str,
    pub email: &'a str,
    pub token: Option<&'a str>,
}